run:
	dotnet run --project MainApp/SystemDefense.csproj

build:
	dotnet build SystemDefense.slnx

clean:
	dotnet clean SystemDefense.slnx

test:
	dotnet run --project MainApp/SystemDefense.csproj -- test
